#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# LN

# git stash --keep-index -u
# git stash --keep-index -u -m STASH_NAME
echo --------- STARTING HUSKY HOOK ---------
# files=$(git diff --cached --name-only)
# echo Staged files [space-separated]: $files

npx lint-staged
npx eslint --ignore-path .gitignore . --fix --max-warnings=0

npx cspell --no-summary --no-progress --gitignore --relative "**/*"
npm run update_browsersList
npx tsc
npm run test
echo --------- FINISHING HUSKY HOOK ---------
# git stash pop
